version: "3"
services:
  soraworld:
    build: 
        context: ../
        dockerfile: ./docker-dev/Dockerfile
    image: soraworld:${TAG:-1.0}
    container_name: soraworld
    restart: unless-stopped
    ports:
      - "0.0.0.0:${HTTP_PORT:-8120}:80"
    environment:
      SERVICE_NAME: soraworld
      SERVICE_TAGS: prod
    working_dir: /var/www/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "mkt.sorasale.vn:host-gateway"
      - "sorasale.vn:host-gateway"
